# Generated by Django 5.2.11 on 2026-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
