# Generated by Django 5.2.11 on 2026-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_comment_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
