# Generated by Django 5.2.11 on 2026-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_count',
            field=models.IntegerField(default=0, verbose_name='Okunma Sayısı'),
        ),
    ]
