# Generated by Django 5.2.11 on 2026-04-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_read_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
