# Generated by Django 5.2.11 on 2026-04-11 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=75, verbose_name='Başlık'),
        ),
    ]
